name: Nomad CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install current SQLite
      uses: ccorsi/setup-sqlite@v1
      with:
        sqlite-version: 3.43.2 # what's in my Macos
        sqlite-year: 2023 # should be correct! see `sqlite3 --version`
    - name: Install dependencies
      run: "pip install .[test]"
    - name: Run tests
      run: "make test"
